# STAGE 1
FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache g++ make py3-pip \
  && npm install -g pnpm

COPY package*.json ./
RUN pnpm install

COPY . .

RUN npm run compile

CMD ["npm", "run", "dev"]
