services:
  sync_service:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    volumes:
      - .:/app
    ports:
      - "3037:3037"
    networks:
      - ambisis-local
    env_file:
      - .env
networks:
  ambisis-local:
    name: ambisis-local
